#server:
#  port: 8086

spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: email-group

  cloud:
    config:
      enabled: false
      import-check:
        enabled: false

  application:
    name: email-service
