spring:
  profiles:
    active: dev
  application:
    name: authentication-service
  datasource:
    driver-class-name: org.postgresql.Driver
  jackson:
    deserialization:
      fail-on-unknown-properties: true # Prevents generating token if client sends invalid json properties.
