server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgres://token-provider-db:5432/token_service_db
    username: user
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      format-sql: true