server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgres://token-provider-db:5432/token_service_db
    username: user
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      format-sql: true

internal:
  endpoints:
    public-key: /api/v1/public-key
    user:
      access-and-refresh-token: /api/v1/user/access-refresh-token
      access-token: /api/v1/user/access-token
      refresh-token: /api/v1/user/refresh-token
    service:
      access-and-refresh-token: /api/v1/service/access-refresh-token
      access-token: /api/v1/service/access-token
      refresh-token: /api/v1/service/refresh-token

#DB_USER: ${DB_USER}
#DB_PASSWORD: ${DB_PASSWORD}
#DB_URL: ${DB_URL}
