server:
  port: 8090

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/test
    username: postgres
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      format-sql: true