spring:
  profiles:
    active: dev
  application:
    name: authentication-service
  datasource:
    driver-class-name: org.postgresql.Driver
  jackson:
    deserialization:
      fail-on-unknown-properties: true



token:
  signing:
    algorithm: RSA
    key-size: 2048
    key-id: payme.auth.id
    rotation-interval-minutes: 60

  encoding:
    type: JWT
    compress: false

  validation:
    clock-skew-seconds: 60

  default-claims:
    audience: payme.internal
    issuer: auth.payme.internal

  templates:
    short-lived:
      validity-minutes: 15
    standard:
      validity-minutes: 60
    long-lived:
      validity-minutes: 120

  profiles:
    user:
      access-token:
        template: short-lived
      refresh-token:
        template: standard

    service:
      access-token:
        template: short-lived
      refresh-token:
        template: standard
      initialization-token:
        template: long-lived