server:
  port: 8090

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/test
    username: postgres
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      format-sql: true

internal:
  endpoints:
    public-key: /public-key
    user:
      access-and-refresh-token: /user/access-refresh-token
      access-token: /user/access-token
      refresh-token: /user/refresh-token
    service:
      access-and-refresh-token: /service/access-refresh-token
      access-token: /service/access-token
      refresh-token: /service/refresh-token

