services:
  token-provider-db:
    image: "postgres:latest"

    restart: always

    ports:
      - 5432:5432

    environment:
      POSTGRES_DB: token_service_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 1234


  token-service:
#    Build an image from the Dockerfile found at this context path
#    (in this case, the same directory .), and use it for this service.
    build:
      context: .
      dockerfile: Dockerfile

# better idea.
    volumes:
      - ~/.m2:/root/.m2 #mount maven local cache to container.6
    restart: always

    depends_on:
      - token-provider-db

    ports:
      - 8080:8080

    environment:
      DB_URL: jdbc:postgres://token-provider-db:5432/token_service_db
      DB_USER: user
      DB_PASSWORD: 1234