services:
  authentication-db:
    image: "postgres:latest"
    restart: always
    ports:
      - 5433:5432
    environment:
      POSTGRES_DB: auth_service_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 1234
    volumes:
      - postgres_data:/var/lib/postgresql/data

  authentication-service:
      build: .
      restart: always
      ports:
        - 8081:8080
      depends_on:
        - authentication-db
        - redis

  redis:
    image: "redis:7-alpine"
    restart: always
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data: