
server:
  port: 8090

spring:
  application:
    name: token-provider
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      format-sql: true

internal:
  endpoints:
    public-key: /public-key
    access-token: /access-token
    refresh-token: /refresh-token

DB_USER: postgres
DB_PASSWORD:
DB_URL: jdbc:postgresql://localhost:5432/test
