
server:
  port: 8080

spring:
  application:
    name: token-provider
  profile:
    active: dev
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      format-sql: true
#  datasource:
#    url: ${DB_URL}
#    username: ${DB_USER}
#    password: ${USER_PASSWORD}

internal:
  endpoints:
    public-key: /api/v1/public-key
    access-token: /api/v1/access-token
    refresh-token: /api/v1/refresh-token


DB_USER: ${DB_USER}
DB_PASSWORD: ${DB_PASSWORD}
DB_URL: ${DB_URL}
#DB_USER: user
#DB_PASSWORD: 1234
#DB_URL: jdbc:postgresql://token-service-db:5432/token_service_db