
spring:
  application:
    name: Tenmo

  datasource:
    url: jdbc:postgresql://localhost:5432/TenmoService
    username: postgres
    password: DeltaMike8816
    driver-class-name: org.postgresql.Driver
    dbcp2:
      test-while-idle: true
      validation-query: select 1

  jpa:
    hibernate:
      ddl-auto: create-drop
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
      format_sql: true
    database: postgresql

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8

logging:
  level:
    org.springframework: INFO
  file:
    path: tenmo-server/server-logs